alias pathable-apply-hotfix="cd /Users/filipenevola/Documents/pathable/ws/deploy/pathable-next/config/jenkins/ && ./apply-hotfix.sh"
alias pathable-prepare-staging-from-development="cd /Users/filipenevola/Documents/pathable/ws/deploy/pathable-next/config/jenkins/ && ./prepare-staging-deploy.sh"
alias pathable-prepare-production-from-development="cd /Users/filipenevola/Documents/pathable/ws/deploy/pathable-next/config/jenkins/ && ./prepare-production-deploy.sh"
alias pathable-prepare-release-patch="cd /Users/filipenevola/Documents/pathable/ws/deploy/pathable-next/config/jenkins/ && ./prepare-release-patch.sh"
alias pathable-copy-production="cd /Users/filipenevola/Documents/pathable/ws/pathable-next/config/db/backups/production && ./copydb.sh"
alias pathable-estore-production="cd /Users/filipenevola/Documents/pathable/ws/pathable-next/config/db/backups/production && ./restoredb.sh"
alias pathable-copy-restore-production="pathable-copy-production && pathable-restore-production"
